- name: install and run nginx
  hosts: web
  become: yes #to run the commands with root access
  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
