- name: variables
  hosts: localhost
  vars: # variable declaration
    Course: "Ansible"
    Trainer: "Vamshi"
    Durartion: "120hrs"
  tasks:
    - name: print override information
      vars: # Task level variables
        Course: "DevOps"
      ansible.builtin.debug:
        msg: "Hi, We are learning {{Course}} from {{Trainer}}, total hrs are {{Durartion}}"

    - name: print information
      ansible.builtin.debug:
        msg: "Hi, We are learning {{Course}} from {{Trainer}}, total hrs are {{Durartion}}"
