- name: data types
  hosts: localhost
  vars:
    Course: DevOps with AWS # String
    Tools: # list
      - Linux
      - Shell
      - Ansible
    Experiance: # map or dictionary
      DevOps: 3 # number
      AWS: 2
      Docker: 1
    RealProject: true #boolean
  tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: "Course: {{Course}}, Tools covered: {{Tools}}, Experiance is: {{Experiance}}, Real project: {{RealProject}}"
