- name: default value
  hosts: localhost
  tasks:
    - name: print default value
      ansible.builtin.debug:
        msg: "hello {{Course | default('Ansible')}}" #if do give variable it takes defafult variable

- name: upper case
  hosts: localhost
  vars:
    greeting: "hello, Good Morning"
  tasks:
    - name: convert into uppercase
      ansible.builtin.debug:
        msg: "{{greeting | upper}}"

- name: lower case
  hosts: localhost
  vars:
    greeting: "hello, Good Morning"
  tasks:
    - name: convert into lowercase
      ansible.builtin.debug:
        msg: "{{greeting | lower}}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1, 2, 3, 4, 4, 5, 5]
  tasks:
    - name: remove duplicates
      ansible.builtin.debug:
        msg: "{{numbers | unique}}"

- name: print min and max
  hosts: localhost
  vars:
    ages: [22, 25, 35, 67, 89]
  tasks:
    - name: print max and min ages
      ansible.builtin.debug:
        msg: "min age: {{ages | min}}, max age {{ages | max}}"

- name: convert dictionary into items/list
  hosts: localhost
  vars:
    my_dist: # this is called as dictionary or map or key/value
      Course: Ansible
      Trainer: vamshi
      Duration: 120hrs
  tasks:
    - name: before convert
      ansible.builtin.debug:
        msg: "Before convert: {{my_dist}}"
    - name: after convert
      ansible.builtin.debug:
        msg: "After convert: {{my_dist | dict2items}}"

- name: convert items/list into dictionary
  hosts: localhost
  vars:
    my_list:
      - { "key": "Course", "value": "Ansible" }
      - { "key": "Trainer", "value": "vamshi" }
      - { "key": "Duration", "value": "120hrs" }
  tasks:
    - name: before convert
      ansible.builtin.debug:
        msg: "Before convert: {{my_list}}"
    - name: after convert
      ansible.builtin.debug:
        msg: "After convert: {{my_list | items2dict}}"
